### ISSUE TITLE
Pom tool should be more descriptive

### ISSUE THREAD

**Issue by mkoncek** [fedora-java/javapackages-bootstrap#128]
It would help if the error message of the pom tool also outputted the line number or the XML node on which it failed.
When the developer sees a message like `Failed to execute tool pom on module commons-parent-pom: null`, they have to inspect the whole pom file again to find why the tool fails.

**Comment by mizdebsk** [comment]
Not reproducible for me - I do see line numbers displayed in case of XML parse errors.
Please provide a reproducer.

**Comment by mkoncek** [comment]
Now I see the plugin name is in the stack trace.
The output after changing the version of `commons-parent-pom` to 61.
```
commons-parent-pom: pom
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.fedoraproject.mbi.tool.Tool.executeInstruction(Tool.java:68)
        at org.fedoraproject.mbi.tool.ToolUtils.runToolOnProject(ToolUtils.java:80)
        at org.fedoraproject.mbi.build.BuildExecutor.completeStep(BuildExecutor.java:116)
        at org.fedoraproject.mbi.build.BuildExecutor.stepCompletionLoop(BuildExecutor.java:157)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Unable to match Plugin(maven-enforcer-plugin)
        at org.fedoraproject.mbi.tool.pom.PomTool.process(PomTool.java:145)
        at org.fedoraproject.mbi.tool.pom.PomTool.removePlugin(PomTool.java:203)
        ... 9 more
Failed to execute tool pom on module commons-parent-pom: null
BUILD FAILURE
```
I reported the bug when attempting the build with java-20, in which case the stack trace was not shown in the followup invocations of build.
