### ISSUE TITLE
Failed to execute tool ant on module qdox

### ISSUE THREAD

**Issue by PureTryOut** [fedora-java/javapackages-bootstrap#159]
Since I think Fedora's policy on packaging Java packages is the way to go for _any_ Linux distribution I'm trying to get this to work on Alpine Linux. However, although the build starts out well it fails on qdox:

```
qdox: ant
org.apache.tools.ant.ExitException: ExitException: status 1
        at org.fedoraproject.mbi.tool.ant.AntTool$1.exit(AntTool.java:96)
        at org.apache.tools.ant.Main.startAnt(Main.java:241)
        at org.fedoraproject.mbi.tool.ant.AntTool.execute(AntTool.java:98)
        at org.fedoraproject.mbi.tool.ToolUtils.runToolOnProject(ToolUtils.java:113)
        at org.fedoraproject.mbi.build.BuildExecutor.completeStep(BuildExecutor.java:116)
        at org.fedoraproject.mbi.build.BuildExecutor.stepCompletionLoop(BuildExecutor.java:161)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Failed to execute tool ant on module qdox
```

This is with 1.20.0 of this repo and sources prepared using `downstream.sh` following the instructions. We're using openjdk21.
Sadly it doesn't seem to give me more information than the exit status so I can't really figure out why it's failing.

**Comment by mizdebsk** [comment]
You can check the ant log at `build/qdox/ant.log`.
I suspect that `byaccj` command is not installed.

**Comment by mizdebsk** [comment]
It should be documented that the build calls 2 non-standard executables:
- byaccj from http://byaccj.sourceforge.net/
- jurand form https://github.com/fedora-java/jurand

**Comment by PureTryOut** [comment]
It was indeed missing `byaccj`, thanks! Good to know where the logs are stored :+1:
