### ISSUE TITLE
./mbi.sh build command occur "Dependency cycle" error

### ISSUE THREAD

**Issue by shouhuanxiaoji** [fedora-java/javapackages-bootstrap#84]
After I clone the code,then I use command ./mbi.sh build,it errors:
```
<xiaoji> sh-5.1# JAVA_HOME=/usr/lib/jvm/java-17 ./mbi.sh build
Exception in thread "main" java.lang.IllegalStateException: Dependency cycle: mbi-pdc -> maven-plugin-tools -> mbi-pdc
        at org.fedoraproject.mbi.plan.BuildPlan.generateBuildSteps(BuildPlan.java:86)
        at org.fedoraproject.mbi.plan.BuildPlan.generateBuildSteps(BuildPlan.java:103)
        at org.fedoraproject.mbi.plan.BuildPlan.generateBuildSteps(BuildPlan.java:92)
        at org.fedoraproject.mbi.plan.BuildPlan.generateBuildSteps(BuildPlan.java:103)
        at org.fedoraproject.mbi.plan.BuildPlan.computeBuildPlan(BuildPlan.java:62)
        at org.fedoraproject.mbi.build.BuildCommand.run(BuildCommand.java:41)
        at org.fedoraproject.mbi.Main.main(Main.java:52)
```
could somebody help me?

**Comment by mizdebsk** [comment]
Hello, can you provide more details?
Which exact commit are you running the command from?
Did you modify any sources?
What JDK are you using?

**Comment by shouhuanxiaoji** [comment]
sorry, there has some error in my harddisk, I have resolved it.
